### PR TITLE
Rename repo

### PR DESCRIPTION
**Pull request by abretaud**
The schedule jenkins job seems to fail due to the repo renaming, so adapting the ci code + :crossed_fingers: 
Can you have a look at restarting the jenkins build after merge @hexylena?

### CODE REVIEW

**Comment by hexylena** [comment]
yeah absolutely

**Comment by hexylena** [comment]
Let's also move under GGA, eh?

**Comment by abretaud** [comment]
oh sure, we can :+1:

**Comment by hexylena** [comment]
I wonder if we can't compile this on GH actions as well, hmm.


> - Job execution time - Each job in a workflow can run for up to 6 hours of execution time. If a job reaches this limit, the job is terminated and fails to complete.
> - Workflow run time - Each workflow run is limited to 35 days. If a workflow run reaches this limit, the workflow run is cancelled. This period includes execution duration, and time spent on waiting and approval.

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
well, we can do in multiple steps.

**Pull request merged**
